name: Build Android APK

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  Build_Android:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version-file: pubspec.yaml
          architecture: x64

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: oracle
          java-version: '17'

      - name: Check Rust toolchain
        run: rustup show

      - name: Install dependencies
        run: flutter pub get

      - name: Build APK (debug)
        run: flutter build apk --debug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: venera-android-apk
          path: build/app/outputs/apk/debug/*.apk
